version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: okt
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    image: nodejs/alpine
    restart: always
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: okt
      DB_HOST: localhost
      DB_PORT: 5432
    ports:
      - "3000:3000"
  client:
    image: nodejs/alpine
    restart: always
    environment:
      API_HOST: localhost
      API_PORT: 3000
    ports:
      - "5173:5173"

volumes:
  pgdata:
